databases:
  - name: tadenetdb
    plan: free
    databaseName: tradenet
    user: tradenet

services:
  - type: web
    plan: free
    name: tradenet
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn tradenet.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: tradenetdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4